(()=>{
const colors={fast:'#e65f2f',balance:'#166bd4',quiet:'#00796f'};
const labels={fast:'Быстрый',balance:'Комфортный',quiet:'Самый тихий'};
let variants=[],activeVariant='balance',pickTarget=null,requestId=0;
const routeWorker=new Worker('./route-worker.js?v=16'),pending=new Map();routeWorker.onmessage=e=>{const p=pending.get(e.data.id);if(!p)return;pending.delete(e.data.id);e.data.error?p.reject(Error(e.data.error)):p.resolve(e.data.variants)};function workerRoutes(s,t,period){return new Promise((resolve,reject)=>{const id=++requestId;pending.set(id,{resolve,reject});routeWorker.postMessage({id,start:s,end:t,period})})}
const legacy=[...document.querySelectorAll('.fields,.modes,.stats,.acoustic,.note')];legacy.forEach(x=>x.classList.add('legacy-hidden'));
const planner=document.createElement('div');planner.className='route-planner';planner.innerHTML=`
 <div>
  <div class="place-row"><div class="place-field"><label for="placeFrom">Откуда</label><input class="place-input" id="placeFrom" list="streetSuggestions" autocomplete="off" placeholder="Введите улицу"></div><button class="swap-places" id="swapPlaces" aria-label="Поменять местами">⇅</button></div>
  <div class="position-box"><span>начало</span><input id="fromPosition" type="range" min="0" max="100" value="50" aria-label="Точка на улице отправления"><span>конец</span></div><div class="place-status" id="fromStatus"></div>
 </div>
 <div>
  <div class="place-row"><div class="place-field"><label for="placeTo">Куда</label><input class="place-input" id="placeTo" list="streetSuggestions" autocomplete="off" placeholder="Введите улицу"></div><span></span></div>
  <div class="position-box"><span>начало</span><input id="toPosition" type="range" min="0" max="100" value="50" aria-label="Точка на улице назначения"><span>конец</span></div><div class="place-status" id="toStatus"></div>
 </div>
 <datalist id="streetSuggestions"></datalist>
 <div class="route-heading"><b>Три варианта маршрута</b><label class="time-field">Когда <select id="timePeriod"><option value="morning">Утро</option><option value="day" selected>День</option><option value="evening">Вечер</option><option value="night">Ночь</option></select></label></div>
 <div class="route-cards" id="routeCards"></div><div class="route-detail" id="routeDetail">Выберите две улицы — приложение сравнит маршруты.</div>`;
document.querySelector('.panel').prepend(planner);
const list=document.querySelector('#streetSuggestions');for(const n of D.streetNames)list.append(new Option(n,n));
const pFrom=document.querySelector('#placeFrom'),pTo=document.querySelector('#placeTo'),fromPos=document.querySelector('#fromPosition'),toPos=document.querySelector('#toPosition');
pFrom.value=from.value;pTo.value=to.value;
const hint=document.createElement('button');hint.className='route-map-hint';hint.textContent='Точки на карте';box.append(hint);
const layerButton=document.createElement('button');layerButton.className='layers-button';layerButton.textContent='Слои';box.append(layerButton);const layerMenu=document.createElement('div');layerMenu.className='layers-menu';layerMenu.innerHTML='<label><input type="checkbox" id="layerNoise" checked> Шум</label><label><input type="checkbox" id="layerCourtyards"> Проходные дворы</label>';box.append(layerMenu);document.querySelector('#noiseButton').classList.add('legacy-hidden');document.querySelector('#courtyardButton').classList.add('legacy-hidden');layerButton.onclick=()=>layerMenu.classList.toggle('open');document.querySelector('#layerNoise').onchange=e=>{showNoise=e.target.checked;requestRender()};document.querySelector('#layerCourtyards').onchange=e=>{showCourtyards=e.target.checked;requestRender()};
function validStreet(name){return D.streetNames.includes(name)}
const preciseStreetCache=new Map();function preciseStreetNodes(name){if(preciseStreetCache.has(name))return preciseStreetCache.get(name);const nodes=[],seen=new Set;for(const w of D.ways)if(w.n===name)for(const p of w.p){const i=lookup.get(p[0].toFixed(7)+','+p[1].toFixed(7));if(i!=null&&component[i]===mainComp&&!seen.has(i)){seen.add(i);nodes.push(i)}}preciseStreetCache.set(name,nodes);return nodes}
function nodeAt(name,percent){const nodes=preciseStreetNodes(name);if(!nodes.length)return null;return nodes[Math.round((nodes.length-1)*percent/100)]}
function describePosition(v){return v<18?'у начала':v>82?'у конца':v<42?'в первой части':v>58?'во второй части':'в середине'}
function updatePlace(which){const input=which==='from'?pFrom:pTo,slider=which==='from'?fromPos:toPos,status=document.querySelector('#'+which+'Status');if(!validStreet(input.value)){status.textContent=input.value?'Выберите улицу из подсказок':'Начните вводить название';return false}const n=nodeAt(input.value,+slider.value);status.textContent=`Выбрано: ${describePosition(+slider.value)} · ${slider.value}% длины`;if(which==='from'){from.value=input.value;start=n;startOptions=null}else{to.value=input.value;end=n;endOptions=null}return n!=null}
function cardHtml(v,fast){if(!v)return'';const delta=v.minutes-fast.minutes;return`<button class="route-card ${v.kind===activeVariant?'active':''}" data-kind="${v.kind}" style="--route-color:${colors[v.kind]}"><span class="route-name"><i class="route-dot"></i>${labels[v.kind]}</span><strong>${v.minutes} мин</strong><small class="comfort comfort-${v.category==='Тихо'?'quiet':v.category==='Умеренно'?'moderate':v.category==='Шумно'?'noisy':'loud'}">${v.category}</small><small>${(v.meters/1000).toFixed(1)} км · модель ~${v.db} дБА</small><small class="delta">${delta?`+${delta} мин`:'быстрее всего'}</small></button>`}
function showVariant(kind,fit=false){const v=variants.find(x=>x?.kind===kind)||variants.find(Boolean);if(!v)return;activeVariant=v.kind;route=v.path;start=route[0];end=route[route.length-1];document.querySelectorAll('.route-card').forEach(c=>c.classList.toggle('active',c.dataset.kind===v.kind));const period=document.querySelector('#timePeriod').selectedOptions[0].text;document.querySelector('#routeDetail').innerHTML=`<b>${labels[v.kind]} · ${v.category}:</b> ${(v.meters/1000).toFixed(1)} км, ${v.minutes} мин. Для периода «${period}» модель оценивает фон примерно в ${v.db} дБА. Тихая часть — ${v.quiet}%, рядом с зеленью — ${v.green}%. Это расчётная категория, не измерение.`;if(fit&&route.length){const ps=(v.geometry||route.map(i=>D.nodes[i])).map(norm),xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]),dx=Math.max(...xs)-Math.min(...xs),dy=Math.max(...ys)-Math.min(...ys);zoom=Math.max(.2,Math.min(5,Math.log2(Math.min((W-50)/(256*Math.max(dx,.001)),(H-70)/(256*Math.max(dy,.001))))));const size=256*2**zoom,mx=(Math.min(...xs)+Math.max(...xs))/2,my=(Math.min(...ys)+Math.max(...ys))/2;ox=-(mx-.5)*size;oy=-(my-.5)*size}requestRender()}
async function renderComparison(fit=false){const detail=document.querySelector('#routeDetail'),cards=document.querySelector('#routeCards');detail.textContent='Сравниваю маршруты в фоновом режиме…';detail.dataset.loading='true';cards.innerHTML='<div class="route-skeleton"></div><div class="route-skeleton"></div><div class="route-skeleton"></div>';try{variants=await workerRoutes(start,end,document.querySelector('#timePeriod').value)}catch{variants=[]}detail.removeAttribute('data-loading');const good=variants.filter(Boolean);if(!good.length){cards.innerHTML='';detail.className='route-error';detail.textContent='Пешеходный маршрут между этими точками не найден.';route=[];requestRender();return}detail.className='route-detail';const fast=variants[0]||good[0];cards.innerHTML=good.map(v=>cardHtml(v,fast)).join('');document.querySelectorAll('.route-card').forEach(c=>c.onclick=()=>showVariant(c.dataset.kind,true));showVariant(activeVariant,fit)}
function compare(fit=false){if(!updatePlace('from')||!updatePlace('to'))return;renderComparison(fit)}
let inputTimer;function changed(which){clearTimeout(inputTimer);inputTimer=setTimeout(()=>{if(updatePlace(which))compare(true)},160)}
pFrom.addEventListener('input',()=>changed('from'));pTo.addEventListener('input',()=>changed('to'));fromPos.addEventListener('input',()=>{updatePlace('from');changed('from')});toPos.addEventListener('input',()=>{updatePlace('to');changed('to')});
document.querySelector('#timePeriod').onchange=()=>renderComparison(false);
document.querySelector('#swapPlaces').onclick=()=>{[pFrom.value,pTo.value]=[pTo.value,pFrom.value];[fromPos.value,toPos.value]=[toPos.value,fromPos.value];compare(true)};
hint.onclick=()=>{pickTarget=pickTarget==='from'?'to':'from';hint.classList.add('pick');hint.textContent=pickTarget==='from'?'Нажмите точку А на карте':'Нажмите точку Б на карте'};
let ignorePointerUntil=0;function commitMapPoint(clientX,clientY){const r=C.getBoundingClientRect(),n=nearest(geo(clientX-r.left,clientY-r.top),true);if(pickTarget==='from'){start=n;startOptions=null;pFrom.value='Точка на карте';document.querySelector('#fromStatus').textContent='Точная точка выбрана на карте'}else{end=n;endOptions=null;pTo.value='Точка на карте';document.querySelector('#toStatus').textContent='Точная точка выбрана на карте'}pickTarget=pickTarget==='from'?'to':null;if(pickTarget)hint.textContent='Нажмите точку Б на карте';else{hint.classList.remove('pick');hint.textContent='Точки на карте';compareNodes(true)}requestRender()}
C.onpointerup=e=>{const wasPinch=!!pinch||touchPoints.size>1;finishTouch(e);if(!pickTarget||performance.now()<ignorePointerUntil||wasPinch||moved){requestRender();return}commitMapPoint(e.clientX,e.clientY)};
C.addEventListener('touchend',e=>{e.preventDefault();e.stopImmediatePropagation();ignorePointerUntil=performance.now()+500;const r=C.getBoundingClientRect();if(e.touches.length===1){const p=nativeTouchPoint(e.touches[0],r);nativePan={x:p.x,y:p.y,ox,oy};nativePinch=null}else if(!e.touches.length){if(pickTarget&&!nativePinch&&!moved&&e.changedTouches.length)commitMapPoint(e.changedTouches[0].clientX,e.changedTouches[0].clientY);nativePinch=null;nativePan=null;nativeTouchActive=false;touchPoints.clear();drag=null;requestRender()}},{capture:true,passive:false});
function compareNodes(fit=false){if(start==null||end==null)return;renderComparison(fit)}
solve=function(){if(start!=null&&end!=null)compareNodes(false)};
const previousDraw=drawOverlay;drawOverlay=function(){ctx.clearRect(0,0,W,H);for(const v of variants.filter(Boolean)){const selected=v.kind===activeVariant,pts=v.geometry||v.path.map(i=>D.nodes[i]);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=selected?'rgba(255,255,255,.96)':'rgba(255,255,255,.72)';ctx.lineWidth=selected?10:6;line(pts);ctx.strokeStyle=colors[v.kind];ctx.globalAlpha=selected?1:.55;ctx.lineWidth=selected?6:3;line(pts);ctx.globalAlpha=1}pin(start,'А','#286b58');pin(end,'Б','#b86e3e')};
compare(true);
})();
