(()=>{
const colors={fast:'#e65f2f',balance:'#166bd4',quiet:'#00796f'};
const labels={fast:'Быстрый',balance:'Комфортный',quiet:'Самый тихий'};
let variants=[],activeVariant='balance',pickTarget=null;
const legacy=[...document.querySelectorAll('.fields,.modes,.stats,.acoustic,.note')];legacy.forEach(x=>x.classList.add('legacy-hidden'));
const planner=document.createElement('div');planner.className='route-planner';planner.innerHTML=`
 <div>
  <div class="place-row"><div class="place-field"><label for="placeFrom">Откуда</label><input class="place-input" id="placeFrom" list="streetSuggestions" autocomplete="off" placeholder="Введите улицу"></div><button class="swap-places" id="swapPlaces" aria-label="Поменять местами">⇅</button></div>
  <div class="position-box"><span>начало</span><input id="fromPosition" type="range" min="0" max="100" value="50" aria-label="Точка на улице отправления"><span>конец</span></div><div class="place-status" id="fromStatus"></div>
 </div>
 <div>
  <div class="place-row"><div class="place-field"><label for="placeTo">Куда</label><input class="place-input" id="placeTo" list="streetSuggestions" autocomplete="off" placeholder="Введите улицу"></div><span></span></div>
  <div class="position-box"><span>начало</span><input id="toPosition" type="range" min="0" max="100" value="50" aria-label="Точка на улице назначения"><span>конец</span></div><div class="place-status" id="toStatus"></div>
 </div>
 <datalist id="streetSuggestions"></datalist>
 <div class="route-heading"><b>Три варианта маршрута</b><span>нажмите карточку, чтобы показать путь</span></div>
 <div class="route-cards" id="routeCards"></div><div class="route-detail" id="routeDetail">Выберите две улицы — приложение сравнит маршруты.</div>`;
document.querySelector('.panel').prepend(planner);
const list=document.querySelector('#streetSuggestions');for(const n of D.streetNames)list.append(new Option(n,n));
const pFrom=document.querySelector('#placeFrom'),pTo=document.querySelector('#placeTo'),fromPos=document.querySelector('#fromPosition'),toPos=document.querySelector('#toPosition');
pFrom.value=from.value;pTo.value=to.value;
const hint=document.createElement('button');hint.className='route-map-hint';hint.textContent='Выбрать точку на карте';box.append(hint);
function validStreet(name){return D.streetNames.includes(name)}
const preciseStreetCache=new Map();function preciseStreetNodes(name){if(preciseStreetCache.has(name))return preciseStreetCache.get(name);const nodes=[],seen=new Set;for(const w of D.ways)if(w.n===name)for(const p of w.p){const i=lookup.get(p[0].toFixed(7)+','+p[1].toFixed(7));if(i!=null&&component[i]===mainComp&&!seen.has(i)){seen.add(i);nodes.push(i)}}preciseStreetCache.set(name,nodes);return nodes}
function nodeAt(name,percent){const nodes=preciseStreetNodes(name);if(!nodes.length)return null;return nodes[Math.round((nodes.length-1)*percent/100)]}
function describePosition(v){return v<18?'у начала':v>82?'у конца':v<42?'в первой части':v>58?'во второй части':'в середине'}
function updatePlace(which){const input=which==='from'?pFrom:pTo,slider=which==='from'?fromPos:toPos,status=document.querySelector('#'+which+'Status');if(!validStreet(input.value)){status.textContent=input.value?'Выберите улицу из подсказок':'Начните вводить название';return false}const n=nodeAt(input.value,+slider.value);status.textContent=`Точка ${describePosition(+slider.value)} улицы`;if(which==='from'){from.value=input.value;start=n;startOptions=null}else{to.value=input.value;end=n;endOptions=null}return n!=null}
function edgeFor(a,b){return adj[a].find(x=>x[0]===b)?.[1]}
function calculate(kind,s,t){const dist=new Float64Array(D.nodes.length);dist.fill(Infinity);const prev=new Int32Array(D.nodes.length);prev.fill(-1);const heap=new Heap;dist[s]=0;heap.push([0,s]);const nf=kind==='fast'?0:kind==='balance'?.9:2.5;while(heap.size){const [du,u]=heap.pop();if(du!==dist[u])continue;if(u===t)break;for(const [v,e]of adj[u]){const mult=Math.max(.42,1+e[3]/100*nf-(e[5]||0)/100*(kind==='quiet'?.45:0)),nd=du+e[2]*mult;if(nd<dist[v]){dist[v]=nd;prev[v]=u;heap.push([nd,v])}}}if(!Number.isFinite(dist[t]))return null;const path=[];for(let u=t;u>=0;u=prev[u]){path.push(u);if(u===s)break}path.reverse();if(path[0]!==s)return null;let meters=0,energy=0,quietMeters=0,greenMeters=0,peak=0;for(let i=1;i<path.length;i++){const e=edgeFor(path[i-1],path[i]);if(!e)continue;const db=segmentDb(e);meters+=e[2];energy+=e[2]*10**(db/10);quietMeters+=db<55?e[2]:0;greenMeters+=(e[5]||0)>=12?e[2]:0;peak=Math.max(peak,db)}const leq=10*Math.log10(energy/(meters||1));return{kind,path,meters,minutes:Math.max(1,Math.round(meters/4700*60)),db:Math.round(leq),quiet:Math.round(quietMeters/(meters||1)*100),green:Math.round(greenMeters/(meters||1)*100),peak:Math.round(peak)}}
function cardHtml(v,fast){if(!v)return'';const delta=v.minutes-fast.minutes;return`<button class="route-card ${v.kind===activeVariant?'active':''}" data-kind="${v.kind}" style="--route-color:${colors[v.kind]}"><span class="route-name"><i class="route-dot"></i>${labels[v.kind]}</span><strong>${v.minutes} мин</strong><small>${(v.meters/1000).toFixed(1)} км · около ${v.db} дБА</small><small>${v.quiet}% тихого пути</small><small class="delta">${delta?`+${delta} мин к быстрому`:'кратчайший по времени'}</small></button>`}
function showVariant(kind,fit=false){const v=variants.find(x=>x?.kind===kind)||variants.find(Boolean);if(!v)return;activeVariant=v.kind;route=v.path;start=route[0];end=route[route.length-1];document.querySelectorAll('.route-card').forEach(c=>c.classList.toggle('active',c.dataset.kind===v.kind));document.querySelector('#routeDetail').innerHTML=`<b>${labels[v.kind]}:</b> ${(v.meters/1000).toFixed(1)} км, ${v.minutes} мин. Средний расчётный фон около ${v.db} дБА, максимум ${v.peak} дБА. Тихая часть — ${v.quiet}%, рядом с зеленью — ${v.green}%.`;if(fit&&route.length){const ps=route.map(i=>norm(D.nodes[i])),xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]),dx=Math.max(...xs)-Math.min(...xs),dy=Math.max(...ys)-Math.min(...ys);zoom=Math.max(.2,Math.min(5,Math.log2(Math.min((W-50)/(256*Math.max(dx,.001)),(H-70)/(256*Math.max(dy,.001))))));const size=256*2**zoom,mx=(Math.min(...xs)+Math.max(...xs))/2,my=(Math.min(...ys)+Math.max(...ys))/2;ox=-(mx-.5)*size;oy=-(my-.5)*size}requestRender()}
function compare(fit=false){if(!updatePlace('from')||!updatePlace('to'))return;document.querySelector('#routeDetail').textContent='Сравниваю маршруты…';setTimeout(()=>{variants=['fast','balance','quiet'].map(k=>calculate(k,start,end));const good=variants.filter(Boolean);if(!good.length){document.querySelector('#routeCards').innerHTML='';document.querySelector('#routeDetail').className='route-error';document.querySelector('#routeDetail').textContent='Пешеходный маршрут между этими точками не найден.';route=[];requestRender();return}document.querySelector('#routeDetail').className='route-detail';const fast=variants[0]||good[0];document.querySelector('#routeCards').innerHTML=good.map(v=>cardHtml(v,fast)).join('');document.querySelectorAll('.route-card').forEach(c=>c.onclick=()=>showVariant(c.dataset.kind,true));showVariant(activeVariant,fit)},20)}
let inputTimer;function changed(which){clearTimeout(inputTimer);inputTimer=setTimeout(()=>{if(updatePlace(which))compare(true)},160)}
pFrom.addEventListener('input',()=>changed('from'));pTo.addEventListener('input',()=>changed('to'));fromPos.addEventListener('input',()=>{updatePlace('from');changed('from')});toPos.addEventListener('input',()=>{updatePlace('to');changed('to')});
document.querySelector('#swapPlaces').onclick=()=>{[pFrom.value,pTo.value]=[pTo.value,pFrom.value];[fromPos.value,toPos.value]=[toPos.value,fromPos.value];compare(true)};
hint.onclick=()=>{pickTarget=pickTarget==='from'?'to':'from';hint.classList.add('pick');hint.textContent=pickTarget==='from'?'Нажмите точку А на карте':'Нажмите точку Б на карте'};
const oldPointerUp=C.onpointerup;C.onpointerup=e=>{if(!pickTarget){oldPointerUp?.(e);return}const wasPinch=!!pinch||touchPoints.size>1;finishTouch(e);if(wasPinch||moved)return;const r=C.getBoundingClientRect(),n=nearest(geo(e.clientX-r.left,e.clientY-r.top),true);if(pickTarget==='from'){start=n;startOptions=null;pFrom.value='Точка на карте';document.querySelector('#fromStatus').textContent='Точная точка выбрана на карте'}else{end=n;endOptions=null;pTo.value='Точка на карте';document.querySelector('#toStatus').textContent='Точная точка выбрана на карте'}pickTarget=pickTarget==='from'?'to':null;if(pickTarget){hint.textContent='Нажмите точку Б на карте'}else{hint.classList.remove('pick');hint.textContent='Выбрать точку на карте';compareNodes(true)}requestRender()};
function compareNodes(fit=false){if(start==null||end==null)return;variants=['fast','balance','quiet'].map(k=>calculate(k,start,end));const good=variants.filter(Boolean),fast=variants[0]||good[0];document.querySelector('#routeCards').innerHTML=good.map(v=>cardHtml(v,fast)).join('');document.querySelectorAll('.route-card').forEach(c=>c.onclick=()=>showVariant(c.dataset.kind,true));showVariant(activeVariant,fit)}
solve=function(){if(start!=null&&end!=null)compareNodes(false)};
const previousDraw=drawOverlay;drawOverlay=function(){ctx.clearRect(0,0,W,H);for(const v of variants.filter(Boolean)){const selected=v.kind===activeVariant,pts=v.path.map(i=>D.nodes[i]);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle=selected?'rgba(255,255,255,.96)':'rgba(255,255,255,.72)';ctx.lineWidth=selected?10:6;line(pts);ctx.strokeStyle=colors[v.kind];ctx.globalAlpha=selected?1:.55;ctx.lineWidth=selected?6:3;line(pts);ctx.globalAlpha=1}pin(start,'А','#286b58');pin(end,'Б','#b86e3e')};
compare(true);
})();
