(()=>{
const map=document.querySelector('#mapbox'),panel=document.querySelector('.panel'),actions=document.querySelector('.mobile-actions');
const routeIcon='<svg viewBox="0 0 24 24"><circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M8 18h3a3 3 0 0 0 3-3V9a3 3 0 0 1 3-3"/></svg>',locateIcon='<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/></svg>',layersIcon='<svg viewBox="0 0 24 24"><path d="m12 3 9 5-9 5-9-5 9-5Z"/><path d="m4 12 8 5 8-5M4 16l8 5 8-5"/></svg>',fitIcon='<svg viewBox="0 0 24 24"><path d="M8 3H3v5M16 3h5v5M21 16v5h-5M3 16v5h5"/></svg>',moreIcon='<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.3" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1.3" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1.3" fill="currentColor" stroke="none"/></svg>';
const shell=document.createElement('div');shell.className='map-search-shell';shell.innerHTML='<div class="app-mark" aria-hidden="true">Т</div><button class="quick-search" id="quickSearch"><span class="quick-placeholder">Поиск улицы или места</span></button><button class="quick-route" id="quickRoute" aria-label="Построить маршрут" title="Построить маршрут">'+routeIcon+'</button>';map.append(shell);
const grab=document.createElement('button');grab.className='sheet-grab';grab.setAttribute('aria-label','Свернуть или развернуть панель');panel.prepend(grab);const summary=document.createElement('button');summary.className='sheet-summary';summary.innerHTML='<span><b>Маршрут</b><br><span id="sheetSummaryText">Выберите точки А и Б</span></span><strong>⌃</strong>';panel.insertBefore(summary,grab.nextSibling);
const tools=document.createElement('div');tools.className='map-tools';tools.innerHTML='<button class="map-tool" id="mapLocate" aria-label="Моё местоположение" title="Моё местоположение">'+locateIcon+'</button><button class="map-tool" id="mapLayers" aria-label="Слои карты" title="Слои карты">'+layersIcon+'</button><button class="map-tool" id="mapFit" aria-label="Показать весь маршрут" title="Показать весь маршрут">'+fitIcon+'</button><button class="map-tool" id="mapMore" aria-label="Ещё" title="Ещё">'+moreIcon+'</button>';map.append(tools);const drawer=document.createElement('div');drawer.className='tools-drawer';if(actions)drawer.append(actions);map.append(drawer);
const pFrom=document.querySelector('#placeFrom'),pTo=document.querySelector('#placeTo'),quick=document.querySelector('#quickSearch'),app=document.querySelector('.app');function syncSheet(){app.classList.toggle('sheet-is-collapsed',panel.classList.contains('sheet-collapsed'))}function expand(){panel.classList.remove('sheet-collapsed');syncSheet()}function focusDestination(){expand();setTimeout(()=>pTo?.focus(),280)}quick.onclick=focusDestination;document.querySelector('#quickRoute').onclick=focusDestination;grab.onclick=()=>{panel.classList.toggle('sheet-collapsed');syncSheet()};summary.onclick=expand;
document.querySelector('#mapLocate').onclick=()=>document.querySelector('#myLocation')?.click();document.querySelector('#mapLayers').onclick=()=>{drawer.classList.remove('open');document.querySelector('.layers-menu')?.classList.toggle('open')};document.querySelector('#mapMore').onclick=()=>{document.querySelector('.layers-menu')?.classList.remove('open');drawer.classList.toggle('open')};document.querySelector('#mapFit').onclick=()=>document.querySelector('.route-card.active')?.click();
document.querySelector('#plus')?.setAttribute('aria-label','Приблизить');document.querySelector('#minus')?.setAttribute('aria-label','Отдалить');
function updateQuick(){const value=pTo?.value?.trim(),span=document.createElement('span');span.textContent=value||'Поиск улицы или места';span.classList.toggle('quick-placeholder',!value);quick.replaceChildren(span)}pTo?.addEventListener('input',updateQuick);updateQuick();
function updateSummary(){const active=document.querySelector('.route-card.active'),text=document.querySelector('#sheetSummaryText');if(!text)return;if(!active){text.textContent='Выберите точки А и Б';return}const time=active.querySelector('strong')?.textContent||'',name=active.querySelector('.route-name')?.textContent?.trim()||'',comfort=active.querySelector('.comfort')?.textContent||'';text.textContent=[time,name,comfort].filter(Boolean).join(' · ')}new MutationObserver(updateSummary).observe(document.querySelector('#routeCards'),{childList:true,subtree:true,attributes:true});updateSummary();
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.tools-drawer,#mapMore'))drawer.classList.remove('open');if(!e.target.closest('.layers-menu,#mapLayers'))document.querySelector('.layers-menu')?.classList.remove('open')});
pin=function(i,t,c){if(i==null)return;const p=screen(D.nodes[i]),x=p[0],y=p[1];ctx.save();ctx.beginPath();ctx.moveTo(x,y+15);ctx.bezierCurveTo(x-3,y+9,x-11,y+5,x-11,y-3);ctx.arc(x,y-3,11,Math.PI,0);ctx.bezierCurveTo(x+11,y+5,x+3,y+9,x,y+15);ctx.closePath();ctx.fillStyle=c;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font='800 10px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t,x,y-3);ctx.restore()};
if(matchMedia('(max-width:759px)').matches)panel.classList.remove('sheet-collapsed');syncSheet();
})();
