import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const required=['index.html','map-content.js','compare-routes.js','compare-routes.css','route-worker.js','sw.js'];for(const file of required)if(!fs.existsSync(path.join(root,file)))throw Error(`Нет обязательного файла: ${file}`);if(fs.existsSync(path.join(root,'data.js')))throw Error('Дублирующий data.js не удалён');
globalThis.self=globalThis;globalThis.importScripts=(url)=>vm.runInThisContext(fs.readFileSync(path.join(root,url),'utf8'),{filename:url});let response=null;self.postMessage=value=>{response=value};vm.runInThisContext(fs.readFileSync(path.join(root,'route-worker.js'),'utf8'),{filename:'route-worker.js'});
const data=self.CH_DATA,lookup=new Map(data.nodes.map((p,i)=>[p[0].toFixed(7)+','+p[1].toFixed(7),i]));function streetNodes(name){const out=[],seen=new Set;for(const way of data.ways)if(way.n===name)for(const p of way.p){const i=lookup.get(p[0].toFixed(7)+','+p[1].toFixed(7));if(i!=null&&!seen.has(i)){seen.add(i);out.push(i)}}return out}
let request=0;function calculate(from,to,period){const a=streetNodes(from),b=streetNodes(to);if(!a.length||!b.length)throw Error(`Нет улицы: ${from} / ${to}`);response=null;self.onmessage({data:{id:++request,start:a[Math.floor(a.length/2)],end:b[Math.floor(b.length/2)],period}});if(!response||response.error)throw Error(response?.error||'Worker не ответил');return response.variants}
const pairs=[['Вознесенский проспект','Невский проспект'],['Вознесенский проспект','Большой проспект В.О.'],['Вознесенский проспект','Чкаловский проспект'],['Садовая улица','Каменноостровский проспект'],['Средний проспект В.О.','Невский проспект']],categories=new Set(['Тихо','Умеренно','Шумно','Очень шумно']);let routes=0;
for(const [from,to]of pairs){let dayFast=null,nightFast=null;for(const period of ['morning','day','evening','night']){const variants=calculate(from,to,period),[fast,balance,quiet]=variants;if(variants.some(v=>!v))throw Error(`Маршрут не найден: ${from} → ${to}, ${period}`);if(fast.meters>balance.meters+1||fast.meters>quiet.meters+1)throw Error('Быстрый маршрут не кратчайший');if(quiet.db>fast.db+0.2)throw Error('Тихий маршрут оказался шумнее быстрого');for(const v of variants){if(!categories.has(v.category))throw Error('Некорректная категория');if(v.path.length<2||v.meters<=0||v.minutes<=0)throw Error('Некорректная геометрия маршрута');routes++}if(period==='day')dayFast=fast;if(period==='night')nightFast=fast}if(nightFast.db>dayFast.db)throw Error('Ночная оценка выше дневной')}
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),client=fs.readFileSync(path.join(root,'compare-routes.js'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');for(const token of ['route-worker.js','compare-routes.js','compare-routes.css'])if(!html.includes(token)&&!sw.includes(token))throw Error(`Ресурс не подключён: ${token}`);if(!client.includes("new Worker('./route-worker.js?v=11')"))throw Error('Web Worker не подключён');if(!client.includes('timePeriod')||!client.includes('layers-button'))throw Error('Нет времени суток или меню слоёв');
console.log(`PASS: ${routes} вариантов, ${pairs.length} контрольных пар, 4 периода времени`);
